export declare const SOCKET_EVENTS: {
    readonly AUTH: "auth";
    readonly DISCONNECT: "disconnect";
    readonly ROOM_JOIN: "room:join";
    readonly ROOM_LEAVE: "room:leave";
    readonly ROOM_CREATE: "room:create";
    readonly ROOM_UPDATE: "room:update";
    readonly ROOM_DELETE: "room:delete";
    readonly ROOM_LIST: "room:list";
    readonly ROOM_GET: "room:get";
    readonly MESSAGE_SEND: "message:send";
    readonly MESSAGE_EDIT: "message:edit";
    readonly MESSAGE_DELETE: "message:delete";
    readonly MESSAGE_HISTORY: "message:history";
    readonly TYPING_START: "typing:start";
    readonly TYPING_STOP: "typing:stop";
    readonly PRESENCE_UPDATE: "presence:update";
    readonly PRESENCE_REQUEST: "presence:request";
    readonly VOICE_JOIN: "voice:join";
    readonly VOICE_LEAVE: "voice:leave";
    readonly VOICE_SIGNAL: "voice:signal";
    readonly VOICE_MUTE: "voice:mute";
    readonly VOICE_UNMUTE: "voice:unmute";
    readonly NOTIFICATION_ACK: "notification:ack";
};
export declare const SOCKET_RESPONSES: {
    readonly CONNECT_SUCCESS: "connect:success";
    readonly CONNECT_ERROR: "connect:error";
    readonly ROOM_JOINED: "room:joined";
    readonly ROOM_LEFT: "room:left";
    readonly ROOM_UPDATED: "room:updated";
    readonly ROOM_DELETED: "room:deleted";
    readonly ROOM_USER_JOINED: "room:user_joined";
    readonly ROOM_USER_LEFT: "room:user_left";
    readonly ROOM_MEMBERS: "room:members";
    readonly MESSAGE_RECEIVED: "message:received";
    readonly MESSAGE_EDITED: "message:edited";
    readonly MESSAGE_DELETED: "message:deleted";
    readonly USER_TYPING: "user:typing";
    readonly USER_STOPPED_TYPING: "user:stopped_typing";
    readonly USER_PRESENCE_CHANGED: "user:presence_changed";
    readonly PRESENCE_LIST: "presence:list";
    readonly VOICE_USER_JOINED: "voice:user_joined";
    readonly VOICE_USER_LEFT: "voice:user_left";
    readonly VOICE_SIGNAL: "voice:signal";
    readonly VOICE_ERROR: "voice:error";
    readonly ERROR: "error";
    readonly PERMISSION_DENIED: "permission:denied";
    readonly NOT_FOUND: "not:found";
    readonly VALIDATION_ERROR: "validation:error";
};
export declare const API_ROUTES: {
    readonly AUTH_LOGIN: "/api/v1/auth/login";
    readonly AUTH_REGISTER: "/api/v1/auth/register";
    readonly AUTH_REFRESH: "/api/v1/auth/refresh";
    readonly AUTH_LOGOUT: "/api/v1/auth/logout";
    readonly AUTH_VERIFY: "/api/v1/auth/verify";
    readonly USERS_ME: "/api/v1/users/me";
    readonly USERS_UPDATE: "/api/v1/users/:id";
    readonly USERS_GET: "/api/v1/users/:id";
    readonly USERS_AVATAR: "/api/v1/users/:id/avatar";
    readonly ROOMS_CREATE: "/api/v1/rooms";
    readonly ROOMS_LIST: "/api/v1/rooms";
    readonly ROOMS_GET: "/api/v1/rooms/:id";
    readonly ROOMS_UPDATE: "/api/v1/rooms/:id";
    readonly ROOMS_DELETE: "/api/v1/rooms/:id";
    readonly ROOMS_JOIN: "/api/v1/rooms/:code/join";
    readonly ROOMS_LEAVE: "/api/v1/rooms/:id/leave";
    readonly ROOMS_MEMBERS: "/api/v1/rooms/:id/members";
    readonly MESSAGES_SEND: "/api/v1/messages";
    readonly MESSAGES_LIST: "/api/v1/rooms/:roomId/messages";
    readonly MESSAGES_GET: "/api/v1/messages/:id";
    readonly MESSAGES_DELETE: "/api/v1/messages/:id";
    readonly FILES_UPLOAD: "/api/v1/files/upload";
    readonly FILES_GET: "/api/v1/files/:id";
    readonly FILES_DELETE: "/api/v1/files/:id";
    readonly NOTIFICATIONS_LIST: "/api/v1/notifications";
    readonly NOTIFICATIONS_MARK_READ: "/api/v1/notifications/:id/read";
};
export declare const ERROR_CODES: {
    readonly INVALID_CREDENTIALS: "INVALID_CREDENTIALS";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly USER_NOT_FOUND: "USER_NOT_FOUND";
    readonly ROOM_NOT_FOUND: "ROOM_NOT_FOUND";
    readonly ROOM_FULL: "ROOM_FULL";
    readonly INVALID_ROOM_CODE: "INVALID_ROOM_CODE";
    readonly ALREADY_IN_ROOM: "ALREADY_IN_ROOM";
    readonly MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND";
    readonly MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG";
    readonly FILE_NOT_FOUND: "FILE_NOT_FOUND";
    readonly FILE_TOO_LARGE: "FILE_TOO_LARGE";
    readonly INVALID_FILE_TYPE: "INVALID_FILE_TYPE";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly PERMISSION_DENIED: "PERMISSION_DENIED";
    readonly RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED";
};
export declare const ROOM_CODE_LENGTH = 9;
export declare const ROOM_CODE_PREFIX = "ROOM";
export declare const ROOM_CODE_CHARSET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
export declare const DEFAULT_PAGE = 1;
export declare const DEFAULT_LIMIT = 20;
export declare const MAX_LIMIT = 100;
export declare const MIN_LIMIT = 1;
export declare const TYPING_INDICATOR_TIMEOUT = 3000;
export declare const PRESENCE_UPDATE_INTERVAL = 30000;
export declare const HEARTBEAT_INTERVAL = 45000;
export declare const MESSAGE_DELETE_DELAY = 86400000;
export declare const CONSTRAINTS: {
    readonly USERNAME_MIN_LENGTH: 3;
    readonly USERNAME_MAX_LENGTH: 20;
    readonly ROOM_NAME_MIN_LENGTH: 3;
    readonly ROOM_NAME_MAX_LENGTH: 100;
    readonly MESSAGE_MAX_LENGTH: 4000;
    readonly FILE_MAX_SIZE: number;
    readonly DESCRIPTION_MAX_LENGTH: 500;
    readonly MAX_ROOM_USERS: 500;
    readonly MIN_ROOM_USERS: 2;
};
export declare const ALLOWED_FILE_TYPES: readonly ["image/jpeg", "image/png", "image/gif", "image/webp", "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/plain", "text/csv", "audio/mpeg", "audio/wav", "video/mp4"];
export declare const WEBRTC_CONFIG: {
    readonly ICE_SERVERS: readonly [{
        readonly urls: "stun:stun.l.google.com:19302";
    }, {
        readonly urls: "stun:stun1.l.google.com:19302";
    }, {
        readonly urls: "stun:stun2.l.google.com:19302";
    }];
    readonly OFFER_OPTIONS: {
        readonly offerToReceiveAudio: true;
        readonly offerToReceiveVideo: false;
    };
};
//# sourceMappingURL=index.d.ts.map